export function getWebviewMessages(locale: string): Record<string, string> {
  if (locale.toLowerCase().startsWith('es')) {
    return {
      appTitle: 'AgenticKanbasutra',
      tagline: 'Workbench personal para planificar, ejecutar y revisar agentes.',
      sidebarTagline: 'Resumen rapido de tus sesiones, cola y configuracion local.',
      summary: 'Resumen',
      configuration: 'Configuracion',
      openBoard: 'Abrir tablero',
      openSettings: 'Abrir configuracion',
      queueActive: 'Cola activa',
      queuePaused: 'Cola pausada',
      queueManual: 'Manual',
      queueAutomatic: 'Automatica',
      queueMode: 'Modo cola',
      groupBy: 'Agrupar',
      groupNone: 'Sin grupo',
      groupRepository: 'Repo',
      groupRunner: 'Runner',
      maxConcurrent: 'Simultaneas',
      recentWork: 'Trabajo reciente',
      newTask: 'Nueva tarea',
      runNext: 'Ejecutar siguiente',
      pauseQueue: 'Pausar cola',
      resumeQueue: 'Reanudar cola',
      cleanup: 'Limpiar finalizadas',
      checkCopilot: 'Comprobar Copilot',
      checkCodex: 'Comprobar Codex',
      checkClaude: 'Comprobar Claude',
      showCompleted: 'Mostrar finalizadas',
      hideCompleted: 'Ocultar finalizadas',
      pending: 'PENDIENTE',
      queued: 'EN COLA',
      running: 'EJECUCION',
      failed: 'FALLIDAS',
      completed: 'FINALIZADA',
      title: 'Titulo',
      spec: 'Spec',
      repository: 'Repositorio',
      branchBase: 'Rama base',
      runner: 'Runner',
      agent: 'Agente',
      model: 'Modelo',
      tools: 'Tools',
      executionMode: 'Modo',
      isolationMode: 'Aislamiento',
      permissionProfile: 'Permisos',
      priority: 'Prioridad',
      saveTask: 'Guardar tarea',
      cancel: 'Cancelar',
      enqueue: 'Encolar',
      requeue: 'Reencolar',
      runNow: 'Ejecutar',
      duplicate: 'Duplicar',
      delete: 'Borrar',
      noTasks: 'Sin tareas',
      output: 'Output',
      close: 'Cerrar',
      expand: 'Expandir',
      collapse: 'Colapsar',
      manualResult: 'Resultado manual',
      manualOutputPlaceholder: 'Pega aqui el resumen, PR, diff, notas o resultado de lo que hiciste fuera de AgenticKanbasutra.',
      completeManualTask: 'Completar tarea manual',
      requiredHint: 'Completa los campos obligatorios para guardar.',
      queueEmpty: 'La cola esta vacia.',
      trustedOnly: 'La ejecucion requiere Workspace Trust.'
    };
  }

  return {
    appTitle: 'AgenticKanbasutra',
    tagline: 'A personal workbench for planning, running, and reviewing agent attempts.',
    sidebarTagline: 'Quick summary of your sessions, queue, and local configuration.',
    summary: 'Summary',
    configuration: 'Configuration',
    openBoard: 'Open board',
    openSettings: 'Open settings',
    queueActive: 'Queue active',
    queuePaused: 'Queue paused',
    queueManual: 'Manual',
    queueAutomatic: 'Automatic',
    queueMode: 'Queue mode',
    groupBy: 'Group',
    groupNone: 'None',
    groupRepository: 'Repo',
    groupRunner: 'Runner',
    maxConcurrent: 'Concurrent',
    recentWork: 'Recent work',
    newTask: 'New task',
    runNext: 'Run next',
    pauseQueue: 'Pause queue',
    resumeQueue: 'Resume queue',
    cleanup: 'Clean completed',
    checkCopilot: 'Check Copilot',
    checkCodex: 'Check Codex',
    checkClaude: 'Check Claude',
    showCompleted: 'Show completed',
    hideCompleted: 'Hide completed',
    pending: 'PENDING',
    queued: 'QUEUED',
    running: 'EXECUTION',
    failed: 'FAILED',
    completed: 'DONE',
    title: 'Title',
    spec: 'Spec',
    repository: 'Repository',
    branchBase: 'Base branch',
    runner: 'Runner',
    agent: 'Agent',
    model: 'Model',
    tools: 'Tools',
    executionMode: 'Mode',
    isolationMode: 'Isolation',
    permissionProfile: 'Permissions',
    priority: 'Priority',
    saveTask: 'Save task',
    cancel: 'Cancel',
    enqueue: 'Enqueue',
    requeue: 'Requeue',
    runNow: 'Run',
    duplicate: 'Duplicate',
    delete: 'Delete',
    noTasks: 'No tasks',
    output: 'Output',
    close: 'Close',
    expand: 'Expand',
    collapse: 'Collapse',
    manualResult: 'Manual result',
    manualOutputPlaceholder: 'Paste the summary, PR, diff, notes, or result from the work completed outside AgenticKanbasutra.',
    completeManualTask: 'Complete manual task',
    requiredHint: 'Complete required fields to save.',
    queueEmpty: 'The queue is empty.',
    trustedOnly: 'Execution requires Workspace Trust.'
  };
}
